spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JAVA_FRAMEWORK
    username: root
    password: 'Capoo840305'
    hikari:
      minimum-idle: '5'
      maximum-pool-size: '10'
      connection-timeout: '30000'
#  JPA config
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  mvc:
    view:
      prefix: /
#  thymeleaf:
#    cache: false
# Spring Web config
server:
  servlet:
    context-path: /cga105g2
# Spring MVC config
  mvc:
    view:
      prefix: /

## Logback config
#logging:
#  level:
#    tw:
#      idv:
#        anthony: debug
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] [%line] %msg%n'
#  file:
#    path: ./

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
